name: MLflow CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.10"
          auto-update-conda: true
          use-mamba: true

      - name: Install MLflow
        shell: bash -l {0}
        run: |
          pip install mlflow==3.7.0

      - name: Run MLflow Project
        shell: bash -l {0}
        env:
          MLFLOW_TRACKING_URI: sqlite:///mlflow.db
        run: |
          export MLFLOW_TRACKING_URI="sqlite:////${{ github.workspace }}/mlflow.db"
          mlflow run MLProject --env-manager=local --experiment-name "CI_RFM_Clustering"

      # ✅ ARTEFAK DISIMPAN → SYARAT SKILLED (3 POIN)
      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: mlruns/

      - name: Upload to Google Drive Folder
        shell: bash -l {0}
        env:
          GDRIVE_CONFIG: ${{ secrets.RCLONE_CONFIG }}
        run: |
          # Install rclone
          sudo apt-get install rclone -y
          
          # Setup konfigurasi rclone dari secret GitHub
          mkdir -p ~/.config/rclone
          echo "$GDRIVE_CONFIG" > ~/.config/rclone/rclone.conf
          
          # Zip folder mlruns (artefak MLflow) agar tidak berantakan
          zip -r model_skilled_artefak.zip mlruns/
          
          # Upload ke folder ID spesifik
          # FORMAT: rclone copy [nama_file] [nama_remote]:[ID_FOLDER]
          rclone copy model_skilled_artefak.zip gdrive:1DoDlBxjw09kEz9TowTYEPzMIWCIPEiup?usp=drive_link
